data_config: &data_config
  type: "bbq"
  debug: false
  subset_size: 10

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "bbq"
      type: "bbq"
      provider: "hf"
      data_config: *data_config
      num_workers: 1
      postprocessor: 
        type: "bbq"

info:
  license: "CC-BY-4.0 License"
  source: "https://github.com/nyu-mll/BBQ"
