config:
  run_id: 1
  model: !include models/default_model.yaml
  seed: 36
  benchmark_configs:
    - name: "fairllm"
      type: "fairllm"
      provider: "hf"
      num_workers: 1
      postprocessor: 
        type: "fairllm"

info:
  license: "None"
  source: "https://github.com/jizhi-zhang/FaiRLLM"
