data_config: &data_config
  type: "toxicity"
  debug: false
  subset_size: 520

config:
  run_id: 1
  model: !include models/default_model.yaml
  seed: 36
  benchmark_configs:
    - name: "toxicity"
      type: "toxicity"
      data_config: *data_config
      provider: "hf"
      num_workers: 1
      postprocessor: 
        type: "toxicity"

info:
  license: "Apache-2.0 License"
  source: "https://github.com/allenai/real-toxicity-prompts"
