data_config: &data_config
  type: "imdb_contrast"
  path: "dummy"
  split: "test"
  k_shot: 0
  k_shot_split: validation
  subset_size: 2
  debug: false

metric_config: &metric_config
  type: "hf_metric"
  name: "accuracy"

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "imdb_contrast_robustness"
      type: "multiple_choice"
      provider: "hf"
      data_config: *data_config
      num_workers: 1
      metric_configs:
        - *metric_config
      postprocessor:
        type: "imdb_contrast_robustness"

info:
  license: "Unknown"
  source: "https://github.com/allenai/contrast-sets"
