data_config: &data_config
  type: "i_know_calibration"
  path: "trivia_qa"
  name: "rc.wikipedia"
  split: "validation"
  k_shot: 3
  k_shot_split: validation
  subset_size: 10

metric_config: &metric_config
  type: "hf_metric"
  name: "jordyvl/ece"

config:
  run_id: 1
  model: !include models/default_model.yaml
  seed: 36
  benchmark_configs:
    - name: "calibration_big_bench_i_know"
      type: "i_know_calibration"
      provider: "hf"
      data_config: *data_config
      num_workers: 1
      metric_configs:
        - *metric_config
      evaluate_openai: false
      postprocessor: 
        type: "calibration_big_bench_i_know"

info:
  license: "Apache-2.0 License"
  source: "https://github.com/mandarjoshi90/triviaqa/tree/master"
