data_config: &data_config
  type: "pii_data"

config:
  run_id: 1
  model: !include models/privacy_model.yaml
  seed: 36
  benchmark_configs:
    - name: "privacy"
      type: "pii_leak"
      provider: "hf"
      data_config: *data_config
      num_workers: 1
      postprocessor: 
        type: "privacy"

info:
  license: "Unknown"
  source: "https://www.cs.cmu.edu/~enron/"
