data_config: &data_config
  type: "hellaswag"
  path: "Rowan/hellaswag"
  split: "validation" # validation since test doesn't contain label
  k_shot: 10
  k_shot_split: train
  subset_size: 10

metric_config: &metric_config
  type: "hf_metric"
  name: "accuracy"

config:
  run_id: 1
  seed: 42
  benchmark_configs:
    - name: "hellaswag"
      type: "hellaswag"
      data_config: *data_config
      metric_configs:
        - *metric_config
      postprocessor:
        type: "hellaswag"

info:
  license: "MIT License"
  source: "https://github.com/rowanz/hellaswag/tree/master"
