data_config: &data_config
  type: "truthful_qa"
  path: "truthful_qa"
  name: "multiple_choice"
  split: "validation"
  k_shot: 0
  subset_size: 10
  mode: "mc2_targets"

config:
  run_id: 1
  model: !include models/default_model.yaml
  seed: 36
  benchmark_configs:
    - name: "truthful_qa_mc2"
      type: "truthful_qa_mc2"
      mode: "mc2_targets"
      provider: "hf"
      data_config: *data_config
      num_workers: 1
      postprocessor:
        type: "truthful_qa_mc2"

info:
  license: "Apache-2.0 License"
  source: "https://github.com/sylinrl/TruthfulQA"
