name: "mistralai/Mistral-7B-Instruct-v0.1" # "meta-llama/Llama-2-7b-hf" #pt2  # google/flan-t5-base
provider: "deepinfra"
type: "causal_lm"
device: "auto"
padding_side: "left"
batch_size: 4
tokenizer_name: "mistralai/Mistral-7B-Instruct-v0.1" # "meta-llama/Llama-2-7b-hf"  # gpt2-xl # google/flan-t5-base
generation_args:
  do_sample: True

