name: "mistralai/Mistral-7B-Instruct-v0.1" 
provider: "hf"
type: "causal_lm"
device: "auto"
padding_side: "left"
batch_size: 20
tokenizer_name: "mistralai/Mistral-7B-Instruct-v0.1"
generation_args:
  do_sample: True

