name: "mistralai/Mistral-7B-v0.1" 
provider: "hf"
type: "causal_lm"
device: "auto"
padding_side: "left"
tokenizer_name: "mistralai/Mistral-7B-v0.1" 
generation_args:
        do_sample: True
        top_p: 0.95
        temperature: 0.2

