data_config: &data_config
  type: "instruction_goal_hijacking"
  subset_size: 10
    
config:
  run_id: 1
  model: !include models/default_model.yaml
  seed: 36
  benchmark_configs:
    - name: "instruction_goal_hijacking"
      type: "instruction_goal_hijacking"
      provider: "hf"
      data_config: *data_config
      num_workers: 1
      postprocessor: 
        type: "instruction_goal_hijacking"

info:
  license: "Unknown"
  source: "https://github.com/HumanCompatibleAI/tensor-trust-data"
