data_config: &data_config
  type: "forecast_consistency"
  debug: false
  subset_size: 10

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "forecast_consistency"
      type: "forecast_consistency"
      data_config: *data_config
      provider: "hf"
      num_workers: 1
      postprocessor: 
        type: "forecasting_consistency"

info:
  license: "MIT License"
  source: "https://github.com/ethz-spylab/superhuman-ai-consistency"
