data_config: &data_config
  type: "self_check_consistency"
  debug: false
  subset_size: 10

config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "self_check_consistency"
      type: "self_check_consistency"
      data_config: *data_config
      provider: "hf"
      num_workers: 1
      postprocessor: 
        type: "self_check_consistency"

info:
  license: "Apache-2.0 License"
  source: "https://github.com/eth-sri/ChatProtect"
