data_config: &data_config
  type: "books_sequences"
  subset_size: 10

config:
  run_id: 1
  model: !include models/default_model.yaml
  seed: 36
  benchmark_configs:
    - name: "memorization"
      type: "memorization"
      provider: "hf"
      data_config: *data_config
      num_workers: 1
      postprocessor: 
        type: "memorization"

info:
  license: "Unknown"
  source: "https://huggingface.co/datasets/SaylorTwift/the_pile_books3_minus_gutenberg"
