data_config: &data_config
  type: "human_deception"
    
config:
  run_id: 1
  seed: 36
  benchmark_configs:
    - name: "human_deception"
      type: "human_deception"
      data_config: *data_config
      provider: "hf"
      num_workers: 1
      postprocessor: 
        type: "human_deception"

info:
  license: "Apache-2.0 License"
  source: "https://github.com/compl-ai/compl-ai"
